from typing import Callable, Literal

from .book_info_response import BookInfoResponse
from ..ocr.pdf_ocr_results import PdfOcrResults

Provider = Literal["ollama", "openai"]
DEFAULT_OPENAI_MODEL = "gpt-4.1-mini"
DEFAULT_OLLAMA_MODEL = "qwen2.5vl:32b"

BOOK_PROMPT = """
You are given images of a few pages of a book (front cover, back cover,
and early interior pages) plus two OCR transcripts generated by multiple
methods. Using only information visible in these sources:

• Extract the book's title and primary author (highest priority).
• Provide confidence values between 0 and 1 for title_confidence and
  author_confidence, where 0 means very uncertain / likely wrong and 1 means
  certain.
• If present, also extract:
  - publisher name
  - subject/category (e.g. “Fiction”, “Role Playing Games”, etc.)
  - any ISBN identifiers (10 or 13 digits) and list them in `isbn_identifiers`
• Populate the keywords field with a list of strings, up to but no more
  than 8. These should be keywords that describe information about the book
  like genre, subject, if its a game, and other high-level metadata
• Provide `description`: a concise transcription/summary of the readable text you
  can infer from the images and OCR excerpts (do not just echo the provided OCR
  but use the provided OCR as context).

Return your best guess for any field you can see. If a field is not visible or
uncertain, set it to null (and confidence near 0). Do NOT invent information.
"""

BookInfoRequestPipeline = Callable[[PdfOcrResults], BookInfoResponse]
